### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CubesterYT** [TurboWarp/scratchblocks#1]
Hello Garbo,

I wanted to ask if there was a way to make terminal blocks using scratchblocks, as I was thinking of changing a block in Window Controls to terminal, and wanted to know if there was a way to make terminal blocks for the markdown docs.

**Comment by GarboMuffin** [comment]
https://scratchblocks.github.io/#?style=scratch3&script=blockname%20%3A%3A%20cap

**Comment by CubesterYT** [comment]
Thank you Garbo!
